chat-machinist:
  visualize: true
  persistence:
    type: mongodb
  bot:
    name: moneyManagerAIbot
    token: secret

gemini:
  api-key: ${GEMINI_API_KEY:secret}
  model: gemini-2.5-flash

debug: false
spring:
  mongodb:
    database: moneyManagerBot
    host: ${MONGO_HOST:localhost}
    username: moneyManagerUser
    password: secret
    port: 27019
  data:
    mongodb:
      auto-index-creation: true
  main:
    banner-mode: off